import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AlertProvider } from "@/components/AlertSystem";
import "./globals.css";
import ThemeToggleGlobal from "@/components/ThemeToggleGlobal";
import Providers from "./providers"; 

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} min-h-dvh bg-white text-slate-900 dark:bg-slate-950 dark:text-slate-100`}>
        <Providers>
          <AlertProvider>
            {children}
            <ThemeToggleGlobal />
          </AlertProvider>
        </Providers>
      </body>
    </html>
  );
}
